bot:
  username: DevValityTgBot
  token: 6342882938:AAHrX5sNoKEJonbjjmBQMylqWSjgg1btEsA

chats:
  tech.vality.chat.id: "-1001994489354"
  all.hands.chat.id: "-1002121227231"
  vality.chat.id: "-1002121227231"