name: Maven Deploy Artifact

on:
  push:
    branches:
      - 'master'

jobs:
  build-and-deploy:
    uses: valitydev/java-workflow/.github/workflows/maven-service-deploy.yml@v2
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      mm-webhook-url: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
